language: go

matrix:
  include:
    - go: "1.10"
      script:
        - go get -t -v ./...
        - go test -race -coverprofile=./coverage.out
        - go test -race -cover -coverprofile=./coverage.txt -covermode=atomic
    - go: 1.11
      script:
        - go get -t -v ./...
        - go test -race -coverprofile=./coverage.out
        - go test -race -cover -coverprofile=./coverage.txt -covermode=atomic
    - go: 1.12
      env:
        - GO111MODULE=on
      install: true
      script:
        - go build
        - go test -race -coverprofile=./coverage.out
        - go test -race -cover -coverprofile=./coverage.txt -covermode=atomic
    - go: 1.13
      env:
        - GO111MODULE=on
      install: true
      script:
        - go build
        - go test -race -coverprofile=./coverage.out
        - go test -race -cover -coverprofile=./coverage.txt -covermode=atomic
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
      after_success:
        - bash <(curl -s https://codecov.io/bash)
