language: go
go:
  - 1.11
  - 1.12

script:
  - go get -t -v ./...
  - go build
  - go test -coverprofile c.out
  - go test -v -cover -race -coverprofile=coverage.txt -covermode=atomic

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - bash <(curl -s https://codecov.io/bash)
