volumes:
  tmp-data: {}
  golint-go: {}
  golint-cache: {}

services:
  # --- Dev tooling ---------------------------------------------------------
  go:
    image: golang:1.25 # Image page: <https://hub.docker.com/_/golang>
    working_dir: /src
    environment:
      HOME: /tmp
      GOPATH: /tmp
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - .:/src:rw
      - tmp-data:/tmp:rw
    security_opt: [no-new-privileges:true]

  golint:
    image: golangci/golangci-lint:v2.7-alpine # Image page: <https://hub.docker.com/r/golangci/golangci-lint>
    environment:
      GOLANGCI_LINT_CACHE: /tmp/golint
    volumes:
      - .:/src:ro
      - golint-go:/go:rw
      - golint-cache:/tmp/golint:rw
    working_dir: /src
    security_opt: [no-new-privileges:true]
